### ISSUE TITLE
Default Formatter

### ISSUE THREAD

**Issue by AyeAyeApi** [AyeAyeApi/Formatters#1]
Currently the format factory will throw an exception if a given format is not found. This is good, but we need a way to check for that, and load a default formatter in this event. This is so that we can still return a response, even if it's in the wrong format.

**Comment by Gisleburt** [comment]
This exception can be caught and handled elsewhere in the app. It would probably be unhelpful to respond with an unexpected default. Aye Aye Api deals with it like this:

https://github.com/AyeAyeApi/Api/blob/1.0.2/src/Api.php#L112-L118
